[globals]
scale = 2

[[badge]]
primary_color = "blue"
secondary_color = "purple"
producer = {
  name = "get-edition",
  crate = "gitoxide"
}

[[badge]]
primary_color = "blue"
secondary_color = "purple"
producer = {
  name = "basic",
  label = "testing",
  status = "123",
}
